"""common — 基础设施模块。"""

from .config_loader import load_config
from .dtypes import DTYPE_INFO, DTYPE_NUMPY, DtypeInfo, dtype_bytes, dtype_c_enum, dtype_numpy
from .errors import (
    AbsorptionError,
    CodegenError,
    CompileDiagnostic,
    CompilerError,
    ConfigError,
    DecompositionError,
    DiagnosticCollector,
    MappingError,
    MemoryPlanError,
    Severity,
    ValidationError,
)
from .graph_ir import (
    ComputeUnit,
    DmaInstruction,
    DmaPlan,
    FormatAnnotation,
    FormatSpec,
    FusionRole,
    Graph,
    Node,
    Storage,
    Tensor,
    TensorFormat,
    graph_diff,
    graph_transaction,
)
from .logger import get_logger, setup_logging
from .compile_config import get_model_config, torch2c_config
from .debug_config import (
    c_mock_compile_level,
    c_mock_runtime_level,
    get_debug_config,
    load_debug_config,
    memory_layout_enabled,
    torch_trace_enabled,
    torch_trace_leaf_only,
)
from .npu_annotate import (
    NpuSpec,
    format_annotation,
    format_model_annotations,
    get_input_annotation,
    get_npu_annotations,
    npu,
    npu_input,
)
from .config_schemas import BlockPadConfig, FormatConfig, MhaMergeConfig
from .pass_config import OptionalPass, PassConfig
from .pass_protocol import CompilerPass, ValidatablePass
from .sizing import align_up, calc_padded_size, get_dim_align
from .torch_debug import (
    disable_trace,
    enable_trace,
    flush_trace,
    get_records,
    trace_context,
)
from .paths import (
    DEFAULT_OUTPUT_DIR,
    HARDWARE_CONFIG_PATH,
    INTEGRATION_CONFIG_DIR,
    NPU_CPU_MOCK_DIR,
    PACKAGE_ROOT,
    PROJECT_ROOT,
)

__all__ = [
    "DEFAULT_OUTPUT_DIR",
    "DTYPE_INFO",
    "DTYPE_NUMPY",
    "AbsorptionError",
    "BlockPadConfig",
    "CodegenError",
    "CompileDiagnostic",
    "CompilerError",
    "ComputeUnit",
    "CompilerPass",
    "ValidatablePass",
    "ConfigError",
    "DecompositionError",
    "DiagnosticCollector",
    "DmaInstruction",
    "DmaPlan",
    "DtypeInfo",
    "FormatAnnotation",
    "FormatConfig",
    "FormatSpec",
    "FusionRole",
    "Graph",
    "graph_diff",
    "HARDWARE_CONFIG_PATH",
    "INTEGRATION_CONFIG_DIR",
    "MappingError",
    "MemoryPlanError",
    "MhaMergeConfig",
    "NPU_CPU_MOCK_DIR",
    "Node",
    "NpuSpec",
    "PACKAGE_ROOT",
    "PROJECT_ROOT",
    "Severity",
    "Storage",
    "Tensor",
    "TensorFormat",
    "ValidationError",
    "get_input_annotation",
    "get_model_config",
    "get_npu_annotations",
    "npu",
    "npu_input",
    "torch2c_config",
    "format_annotation",
    "format_model_annotations",
    "dtype_bytes",
    "dtype_c_enum",
    "dtype_numpy",
    "get_logger",
    "load_config",
    "setup_logging",
    "enable_trace",
    "disable_trace",
    "flush_trace",
    "get_records",
    "trace_context",
    "load_debug_config",
    "get_debug_config",
    "torch_trace_enabled",
    "torch_trace_leaf_only",
    "memory_layout_enabled",
    "c_mock_compile_level",
    "c_mock_runtime_level",
    "align_up",
    "calc_padded_size",
    "get_dim_align",
]
